openapi: "3.0.0"
info:
  title: TODO API
  version: "0.0.1"
  description: TODO API Documentです
tags:
  - name: opts
    description: 運用監視API
  - name: tasks
    description: タスクAPI
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK

  /tasks/:
    get:
      summary: "タスク一覧取得"
      description: "タスク一覧を取得します"
      tags:
        - tasks
      operationId: fetchTasks
      parameters:
        - name: limit
          in: query
          required: true
          description: "リストに含まれるリソースの最大値"
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 20
            default: 10
        - name: offset
          in: query
          required: true
          description: "オフセット"
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              ## メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/TaskDtoList"
        '400':
          description: Bad Request
          content:
            application/json:
              # メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/BadRequestError"
    post:
      summary: "タスク追加"
      description: "タスクを新規作成します"
      tags:
        - tasks
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            ## メディアタイプオブジェクト
            schema:
              $ref: "#/components/schemas/TaskForm"
      responses:
        "201":
          description: "Created"
          headers:
            location:
              description: "作成されたリソースのURI"
              schema:
                type: string
          content:
            application/json:
              ## メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '400':
          description: "Bad Request"
          content:
            application/json:
              # メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/BadRequestError"

  /tasks/{taskId}:
    put:
      summary: "タスク更新"
      description: "指定されたタスクをリクエストボディの内容で上書きします"
      tags:
        - tasks
      operationId: editTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: "更新するタスクのID"
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            ## メディアタイプオブジェクト
            schema:
              $ref: "#/components/schemas/TaskForm"
      responses:
        '200':
          description: OK
          content:
            application/json:
              ## メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '400':
          description: "Bad Request"
          content:
            application/json:
              # メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/BadRequestError"
        '404':
          description: Not Found
          content:
            application/json:
              # メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
    get:
      summary: "タスク取得"
      description: "指定した条件でタスクを取得します"
      tags:
        - tasks
      operationId: fetchTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: "詳細を取得するタスクのID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              ## メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '400':
          description: Not Found
          content:
            application/json:
              # メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
    delete:
      summary: "タスク削除"
      description: "指定したタスクを削除します"
      tags:
        - tasks
      operationId: deleteTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: "削除するタスクのID"
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: "No Content"
        '404':
          description: Not Found
          content:
            application/json:
              # メディアタイプオブジェクト
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"

components:
  schemas:
    TaskForm:
      type: object
      properties:
        title:
          type: string
          description: "タスクのタイトル"
          maxLength: 256
          minLength: 1
      required:
        - title

    TaskDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "タスクID"
        title:
          type: string
          description: "タスクのタイトル"
      required:
        - id
        - title

    TaskDtoList:
      type: object
      properties:
        page:
          $ref: "#/components/schemas/PageDto"
        results:
          type: array
          items:
            $ref: "#/components/schemas/TaskDTO"
      required:
        - results

    PageDto:
      description: "ページング情報"
      type: object
      properties:
        limit:
          description: "リクエストされたlimit"
          type: integer
          format: int32
        offset:
          description: "リクエストされたoffset"
          type: integer
          format: int64
        size:
          description: "取得できた件数"
          type: integer
          format: int32
      required:
        - limit
        - offset
        - size


    # RFC7807 HTTP APIのエラーレスポンス規格
    # https://datatracker.ietf.org/doc/html/rfc7807
    ResourceNotFoundError:
      description: "指定したリソースが存在しない"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Resource Not Found"
        detail:
          type: string
          description: "Resource Not Found"
      required:
        - title
        - detail

    BadRequestError:
      description: "リクエストが不正です。"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Bad Request"
        detail:
          type: string
          description: "エラーの詳細"
          default: "リクエストが不正です。正しいリクエストでやり直してください"
        invalid-params:
          type: array
          items:
            $ref: "#/components/schemas/InvalidParam"
      required:
        - title
        - detail
        - invalid-params

    InvalidParam:
      description: "不正なリクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: "エラーのタイトル"
          default: "Bad Request"
        reason:
          type: string
          description: "エラーの詳細"
          default: "Resource Not Found"
      required:
        - name
        - reason




